MyWebSite/Controllers/AvatarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MyMVCWeb.Models;
using System.Web.Routing;

namespace MyMVCWeb.Controllers
{
    public class AvatarController : Controller
    {
        private UsersContext db = new UsersContext();

        const string defaultavatar = "~/Images/金馆长.jpg";
        //
        // GET: /Avatar/Show/name
        public ActionResult Show(string name=null)
        {
            var pics = db.Avatars;
            if (name == null)
            {
                MembershipUser user = Membership.GetUser();
                if (user != null)
                {

                    try
                    {
                        Pictures PicData = pics.Where(p => p.PicName == user.UserName).First();
                        return File(PicData.Data, PicData.PicType);
                    }
                    catch
                    {
                        return File(Server.MapPath(defaultavatar), "image/jpeg");
                    }

                }
                else
                {
                    return File(Server.MapPath(defaultavatar), "image/jpeg");
                    //Response.Redirect("~/Default.aspx");
                }

            }
            else
            {
                Pictures PicData = pics.FirstOrDefault(p => p.PicName == name);
                if (PicData != null)
                {
                    return File(PicData.Data, PicData.PicType);
                }
                else
                {
                    return File(Server.MapPath(defaultavatar), "image/jpeg");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyWebSite/Controllers/ReplyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyMVCWeb.Models;
using PagedList;

namespace MyMVCWeb.Controllers
{
    public class ReplyController : Controller
    {
        public ReplyController()
            : base()
        {
            object size = System.Web.HttpContext.Current.Application["ReplyPagesize"];
            if (size is int)
                replypagesize = (int)size;
            else
                replypagesize = _replypagesize;
        }
        private int replypagesize;
        private const int _replypagesize = 10;
        private BlogContext db = new BlogContext();


        [ValidateInput(false)]
        [HttpPost]
        [Authorize]
        public ActionResult AddReply(string itemid, string addreplycontent, string Captcha, string Prefix, string idtype = "1")
        {
            int id = int.Parse(itemid);
            //dynamic viewModel = new ExpandoObject();
            var viewModel = id;
            if (BlogUtil.checkCaptchaError(Captcha, Prefix))
            {
                ModelState.AddModelError("Captcha", "验证码计算错误，请重试。");
                return PartialView(viewModel);
            }
            DateTime? lastpost = Session["LastPostTime"] as DateTime?;
            if (lastpost.HasValue)
            {
                var diff = DateTime.Now - lastpost.Value;
                if (diff.TotalSeconds < 30)
                {
                    ModelState.AddModelError("添加回复", "回复CD为30秒，请等" + (30 - diff.Seconds) + "秒后再试");
                    return PartialView(viewModel);
                }
            }
            if (string.IsNullOrWhiteSpace(BlogUtil.removeAllTags(addreplycontent)))
            {
                ModelState.AddModelError("添加回复", "回复不能为空");
                return PartialView(viewModel);
            }
            else if (!BlogUtil.checkContentTags(addreplycontent))
            {
                ModelState.AddModelError("添加回复", "不许内嵌代码！！！");
                return PartialView(viewModel);
            }

            Post np = new Post();
            int i;
            if (idtype == "2")
                i = BlogUtil.AddTopicPost(id, User.Identity.Name, addreplycontent);
            else
                i = BlogUtil.AddPost(id, User.Identity.Name, addreplycontent);
            Session["LastPostTime"] = DateTime.Now;
            return Json(new { redirect = "#listpost" + i });
        }

        [ValidateInput(false)]
        [HttpPost]
        [Authorize]
        public JsonResult AddPostReply(string postid, string addreplycontent)
        {
            int id = int.Parse(postid);
            //dynamic viewModel = new ExpandoObject();
            var viewModel = id;
            DateTime? lastpost = Session["LastPostTime"] as DateTime?;
            if (lastpost.HasValue)
            {
                var diff = DateTime.Now - lastpost.Value;
                if (diff.TotalSeconds < 30)
                {
                    return Json(new { errmsg = "回复CD为30秒，请等" + (30 - diff.Seconds) + "秒后再试" });
                }
            }
            if (string.IsNullOrWhiteSpace(BlogUtil.removeAllTags(addreplycontent)))
            {
                return Json(new { errmsg = "回复不能为空" });
            }
            else if (!BlogUtil.checkContentTags(addreplycontent))
            {
                return Json(new { errmsg = "不许内嵌代码！！！" });
            }

            Post np = new Post();
            int i = BlogUtil.AddPostReply(id, User.Identity.Name, addreplycontent);
            Session["LastPostTime"] = DateTime.Now;
            return Json(new { id = i });
        }

        [HttpPost]
        public JsonResult DeleteReply(string replyid)
        {

            int id = int.Parse(replyid);
            var post = db.Replies.Find(id);
            if (post == null)
                return Json(new { errmsg = "无效的id" });
            if (post.Author != User.Identity.Name && !User.IsInRole("Administrator") && !User.IsInRole("Moderator"))
            {
                return Json(new { errmsg = "你tmd没权限删除" });
            }
            db.Replies.Remove(post);
            db.SaveChanges();
            return Json(true);
        }

        [HttpGet]
        public ActionResult ShowReply(string itemid, string idtype = "1")
        {
            int id = int.Parse(itemid);
            int num = 1;
            List<Post> posts;
            if (idtype == "2")
            {
                var blog = db.Topics.Find(id);
                if (blog == null)
                    return HttpNotFound();
                posts = blog.Posts;
            }
            else
            {
                var blog = db.Blogs.Find(id);
                if (blog == null)
                    return HttpNotFound();
                posts = blog.posts;
            }
            posts.Reverse();
            ViewData["idtype"] = idtype;
            ViewData["itemid"] = itemid;
            return PartialView(posts.ToPagedList(num, replypagesize));
        }
        [HttpPost]
        public ActionResult ShowReply(string itemid, string pagenum, string idtype = "1")
        {
            int pagesize = replypagesize;
            int id = int.Parse(itemid);
            int num = int.Parse(pagenum);
            IEnumerable<Post> posts;
            if(idtype == "2"){
                var blog = db.Topics.Find(id);
                if (blog == null)
                    return HttpNotFound();
                posts = blog.Posts;
            }
            else{
                var blog = db.Blogs.Find(id);
                if (blog == null)
                    return HttpNotFound();
                posts = blog.posts;
            }
            posts.Reverse();
            ViewData["idtype"] = idtype;
            ViewData["itemid"] = itemid;
            int pagecount = (int)Math.Ceiling((double)posts.Count() / pagesize);
            if (num <= 0 || num > pagecount)
            {
                num = 1;
            }
            return PartialView(posts.ToPagedList(num, pagesize));
        }

        [HttpGet]
        public ActionResult ShowUserReply(string itemid, string name, string idtype = "1")
        {
            int pagesize = replypagesize;
            int id = int.Parse(itemid);
            int num = 1;
            IEnumerable<Post> posts;
            if (idtype == "2")
            {
                var blog = db.Topics.Find(id);
                if (blog == null)
                    return HttpNotFound();
                posts = blog.Posts.Where(p => p.Author == name);
            }
            else
            {
                var blog = db.Blogs.Find(id);
                if (blog == null)
                    return HttpNotFound();
                posts = blog.posts.Where(p => p.Author == name);
            }
            posts.Reverse();
            ViewData["idtype"] = idtype;
            ViewData["itemid"] = itemid;
            ViewBag.relplyusername = name;
            return PartialView("ShowReply", posts.ToPagedList(num, pagesize));
        }
        [HttpPost]
        public ActionResult ShowUserReply(string itemid, string name, string pagenum, string idtype = "1")
        {
            int pagesize = replypagesize;
            int id = int.Parse(itemid);
            int num = int.Parse(pagenum);
            IEnumerable<Post> posts;
            if (idtype == "2")
            {
                var blog = db.Topics.Find(id);
                if (blog == null)
                    return HttpNotFound();
                posts = blog.Posts.Where(p => p.Author == name);
            }
            else
            {
                var blog = db.Blogs.Find(id);
                if (blog == null)
                    return HttpNotFound();
                posts = blog.posts.Where(p => p.Author == name);
            }
            posts.Reverse();
            ViewData["idtype"] = idtype;
            ViewData["itemid"] = itemid;
            int pagecount = (int)Math.Ceiling((double)posts.Count() / pagesize);
            if (num <= 0 || num > pagecount)
            {
                num = 1;
            }
            return PartialView("ShowReply", posts.ToPagedList(num, pagesize));
        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize]
        public ActionResult EditReply(string PostId, string content)
        {
            int id = int.Parse(PostId);
            var post = db.Posts.Find(id);
            if (post == null)
                return HttpNotFound();
            if (post.Author != User.Identity.Name && !User.IsInRole("Administrator") && !User.IsInRole("Moderator"))
            {
                return Json(new { errmsg = "你tmd没权限更改" });
            }
            else if (string.IsNullOrWhiteSpace(content))
            {
                return Json(new { errmsg = "回复不能为空" });
            }
            else if (!BlogUtil.checkContentTags(content))
            {
                return Json(new { errmsg = "不许内嵌代码！！！" });
            }
            post.Content = content;
            db.SaveChanges();
            return Json(true);
        }
        [HttpPost]
        public ActionResult DeletePost(string PostId)
        {
            int id = int.Parse(PostId);
            var post = db.Posts.Find(id);
            if (post == null)
                return HttpNotFound();
            if (post.Author != User.Identity.Name && !User.IsInRole("Administrator") && !User.IsInRole("Moderator"))
            {
                return Json(new { errmsg = "你tmd没权限删除" });
            }
            db.Posts.Remove(post);
            db.SaveChanges();
            return Json(true);
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyWebSite/Views/Reply/ShowReply.cshtml
@model PagedList.IPagedList<MyMVCWeb.Models.Post>
<input type="hidden" id="curpagenum" value="@Model.PageNumber"/>
@foreach(Post post in Model)
{
    int index = 0;
    <table style="width:100%" id ="@("listpost"+post.PostId)" class="replytable">
                <colgroup>
                   <col span="1" style="width: 100px;"/>
                   <col span="1" />
                </colgroup>
                <tr>
                    <td rowspan="3" class="replyavatar"><a href="@Url.Action("UserInfo","Home",new {name = post.Author})"><img src="@Url.Action("Show","Avatar",new {name = post.Author})" style="max-height:100px;max-width:100px;" /></a></td>
                    <td style="text-align:left; padding-left:2em;">@Html.ActionLink(post.Author, "UserInfo","Home",new {name = post.Author},null) 发表于 @post.PostDate
                        &nbsp;
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a onclick="reply(@post.PostId);">回复</a>
                            int itemid = 0;
                            if (post.BlogId.HasValue)
                            {
                                itemid = post.BlogId.Value;
                            }
                            else if (post.TopicId.HasValue)
                            {
                                itemid = post.TopicId.Value;
                            }
                            if(itemid>0){
                            <a onclick="rptReply(@post.PostId);" data-toggle="modal" role="button" href="#rptModal" class="hovershow">举报</a>@Html.Raw("  ")
                            }
                            
                        }
                        &nbsp;
                        @if(User.IsInRole("Administrator") || User.IsInRole("Moderator") || User.Identity.Name == post.Author)
                        {
                            <a onclick="editreply(@post.PostId);" class="hovershow">编辑</a>@Html.Raw("  ")
                            <a onclick="delreply(@post.PostId);" class="hovershow">删除</a>
                        }
                    </td>
                </tr>
                <tr>
                    <td style="padding-left:2em;"><div id='postcontent@(post.PostId)' class="bubble">
                        <div class="reply">
                            @Html.Raw(post.Content)
                        </div>
                        <div style="display:none;" id="btnarea_@post.PostId">
                        @if(User.IsInRole("Administrator") || User.IsInRole("Moderator") || User.Identity.Name == post.Author)
                        {
                            <input type="button" id="editreplybtn_@post.PostId" value ="提交" class="btn btn-small" onclick="@string.Format("editclick({0},'{1}');", post.PostId, Url.Action("EditReply")) " >
                            @Html.Raw(" ")
                            <input type="button" id="canceleditbtn_@post.PostId" value ="取消" class="btn btn-small" onclick="cancelclick();">
                            <span class = "field-validation-error" id ="editerror_@post.PostId"></span>
                        }
                        </div>
                        @if(post.repies.Count > 0){
                        <div class="postreply">
                            <ul data-postid="@post.PostId">
                            @foreach (var reply in post.repies)
	                        {
                                <li id="reply@(reply.ReplyId)">
                                    <a class="avatar" href="@Url.Action("UserInfo","Home",new {name = reply.Author})"><img src="@Url.Action("Show","Avatar",new {name = reply.Author})" /></a>
                                    <div class="reply">
                                        <span class="replyact">
                                        @if (User.IsInRole("Administrator") || User.IsInRole("Moderator") || User.Identity.Name == reply.Author)
                                        {
                                            <span class="del">
                                                <a onclick="delPostReply(@reply.ReplyId)">删除</a>@Html.Raw(" | ")
                                            </span>
                                        }
                                        @reply.ReplyDate 
					@if (User.Identity.IsAuthenticated){
						<a onclick="replyreply(@reply.ReplyId,'@reply.Author')" >回复</a>
					}</span>
                                        <a href="@Url.Action("UserInfo","Home",new {name = reply.Author})">@reply.Author</a><br />
                                        @Html.Raw(reply.Content)
                                    </div>
                                </li>
	                        }
                            </ul>
                        </div>
                        }
                        <div class="addReply hide">
                            <textarea style="visibility:hidden"></textarea>
                            <button onclick="replyPost(@post.PostId)" style="margin-top: 2px" class="btn btn-small btn-primary">发表</button>
                            <button style="margin-top: 2px" class="btn btn-small" onclick="cancelclick();">取消</button>
                        </div>
                    </div>
                    </td>
                </tr>
            </table>
    index++;
}
@if (!Model.IsFirstPage || !Model.IsLastPage)
{
    Html.RenderPartial("_AjaxPager", Model);
}
<style>
    .trans {
        -moz-transition: background-color linear 2s;
        -o-transition: background-color linear 2s;
        -webkit-transition: background-color linear 2s;
        transition: background-color linear 2s;
    }
</style>
<script>
    $(function () {
        if (location.hash && (location.hash.indexOf("listpost") != -1 || location.hash.indexOf("reply") != -1)) {
            $(location.hash).css("background-color", "lightGrey").delay(3000).queue(function () {
                $(this).addClass('trans').css("background-color", "inherit");
            });
        }
    });
    var replyposturl = "@Url.Action("AddPostReply","Reply")";
</script>

MyWebSite/Views/Reply/_AjaxPager.cshtml
@model PagedList.IPagedList

@{string displayid = "replydiv";
  string itemid = ViewData["itemid"] as string;
  string idtype = ViewData["idtype"] as string;
  string name = ViewBag.relplyusername as string;
  }

<div class="pager">
    @if (Model.HasPreviousPage)
    {
        <a class="btn btn-mini" onclick="postgotopage(1);">第1页</a>
        @Html.Raw(" ")
        <a class="btn btn-mini" onclick="postgotopage(@Model.PageNumber-1);">上一页</a>
    }
    else{
        <a class="btn btn-mini disabled">第1页</a>@Html.Raw(" ")<a class="btn btn-mini disabled">上一页</a>
    }
    @{string lastpage = "第"+Model.PageCount+"页";}
    @if (Model.HasNextPage)
    {
        <a class="btn btn-mini" onclick="postgotopage(@Model.PageNumber+1);">下一页</a>
        @Html.Raw(" ")
        <a class="btn btn-mini" onclick="postgotopage(@Model.PageCount);">@lastpage</a>
    }
    else{
        @:<a class="btn btn-mini disabled">下一页</a> <a class="btn btn-mini disabled">@lastpage</a>
    }
    &nbsp;
    <span>第
        @Html.TextBox("postjumppage", Model.PageNumber, new {style="width: 2em;height: 1em;padding: 3px;margin: 0px;" })
       页</span> 
    <script>
        $(function(){
            $('#postjumppage').change(function () {
                var pagenum = parseInt(this.value);
                var pagecount = '@Model.PageCount';
                if (pagenum > 0 && pagenum <= pagecount) {
                    gotopage(pagenum);
                }
            });
        });
        function postgotopage(pagenum) {
            var pagecount = '@Model.PageCount';
            if (pagenum > 0 && pagenum <= pagecount) {
                @if(name == null){
                <text>$.post('@Url.Action("ShowReply")', { itemid: '@blogid', pagenum: pagenum, idtype: '@idtype' }, postreplace);</text>
                }
                else{
                 <text>$.post('@Url.Action("ShowUserReply")', { itemid: '@blogid', name: '@name', pagenum: pagenum, idtype: '@idtype' }, postreplace); </text>   
                }
            }
        }
        function postreplace(result) {
            $('#@displayid').html(result);
        }
    </script>
</div>