MyWebSite/Controllers/AvatarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MyMVCWeb.Models;
using System.Web.Routing;

namespace MyMVCWeb.Controllers
{
    public class AvatarController : Controller
    {
        private UsersContext db = new UsersContext();

        const string defaultavatar = "~/Images/金馆长.jpg";
        //
        // GET: /Avatar/Show/name
        public ActionResult Show(string name=null)
        {
            var pics = db.Avatars;
            if (name == null)
            {
                MembershipUser user = Membership.GetUser();
                if (user != null)
                {

                    try
                    {
                        Pictures PicData = pics.Where(p => p.PicName == user.UserName).First();
                        return File(PicData.Data, PicData.PicType);
                    }
                    catch
                    {
                        return File(Server.MapPath(defaultavatar), "image/jpeg");
                    }

                }
                else
                {
                    return File(Server.MapPath(defaultavatar), "image/jpeg");
                    //Response.Redirect("~/Default.aspx");
                }

            }
            else
            {
                Pictures PicData = pics.FirstOrDefault(p => p.PicName == name);
                if (PicData != null)
                {
                    return File(PicData.Data, PicData.PicType);
                }
                else
                {
                    return File(Server.MapPath(defaultavatar), "image/jpeg");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyWebSite/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyMVCWeb.Models;
using PagedList;

namespace MyMVCWeb.Controllers
{
    public class TopicController : Controller
    {
        public TopicController():base()
        {
            object size = System.Web.HttpContext.Current.Application["ListPagesize"];
            if (size is int)
                listpagesize = (int)size;
            else
                listpagesize = _listpagesize;
            size = System.Web.HttpContext.Current.Application["ReplyPagesize"];
            if (size is int)
                replypagesize = (int)size;
            else
                replypagesize = _listpagesize;
        }

        private const int _listpagesize = 18;
        private const int _replypagesize = 10;

        private int listpagesize;
        private int replypagesize;

        private BlogContext db = new BlogContext();

        //
        // GET: /Topic/

        public ActionResult List(int? id, int page = 1, string sort = "")
        {
            var topics = db.Topics.Include(t => t.tag);
            if (id.HasValue && id.Value > 0)
            {
                if (db.Categories.Find(id.Value) == null)
                    return HttpNotFound();
                topics = topics.Where(b => b.CategoryID == id);
            }
            ViewBag.DateSortParm = String.IsNullOrEmpty(sort) ? "Date" : "";
            ViewBag.VisitSortParm = sort == "Visit_desc" ? "Visit" : "Visit_desc";
            ViewBag.UpdateSortParm = sort == "Update_desc" ? "Update" : "Update_desc";
            ViewBag.PostSortParm = sort == "Post_desc" ? "Post" : "Post_desc";
            ViewBag.CurrentSort = sort;
            topics = BlogUtil.getSortedQuery(topics, sort);

            int pagecount = (int)Math.Ceiling((double)topics.Count() / listpagesize);
            int pagenumber;
            if (page > 0 && page <= pagecount)
            {
                pagenumber = page;
            }
            else
            {
                pagenumber = 1;
            }
            return View(topics.ToPagedList(pagenumber, listpagesize));
        }

        //
        // GET: /Topic/Details/5

        public ActionResult Details(int id = 0)
        {
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            var model = new TopicDisplay();
            model.topic = topic;
            model.blogs = db.BlogsInTopics.Where(t => t.TopicID == topic.TopicID).OrderBy(t=>t.BlogOrder).Select(t => t.blog).ToList();
            //model.blogs.Reverse();
            topic.TopicVisit++;
            db.SaveChanges();
            return View(model);
        }

        //
        // GET: /Topic/Create
        [Authorize(Roles = "Writers,Administrator,Moderator")]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        //
        // POST: /Topic/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Writers,Administrator,Moderator")]
        [ValidateInput(false)]
        public ActionResult Create(TopicEdit topic)
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            if (ModelState.IsValid)
            {
                Topic ntopic = new Topic();
                int ret = BlogUtil.CheckBlogTag(topic.TagName, 1);
                if (ret != 0)
                {
                    ModelState.AddModelError("", ret > 0 ? "专题标签只能有1个" : "标签不得超过20个字符");
                    return View(topic);
                }
                if (!BlogUtil.checkContentTags(topic.Content))
                {
                    ModelState.AddModelError("", "不许内嵌代码！警察叔叔就是这个人！！！！");
                    return View(topic);
                }
                ntopic.Author = User.Identity.Name;
                ntopic.CategoryID = topic.CategoryID;
                ntopic.Content = topic.Content;
                ntopic.CreateDate = DateTime.Now;
                ntopic.UpdateDate = DateTime.Now;
                ntopic.TopicVisit = 0;
                ntopic.TopicTitle = topic.TopicTitle;
                try
                {
                    var tag = db.Tags.SingleOrDefault(t => t.TagName == topic.TagName);
                    if (tag == null)
                    {
                        tag = new Tag { TagName = topic.TagName };
                    }
                    ntopic.tag = tag;
                    db.Topics.Add(ntopic);
                    int i = 0;
                    foreach (var id in topic.blogIDs)
                    {
                        Blog b = db.Blogs.Find(id);
                        if (b == null)
                        {
                            ModelState.AddModelError("", "未找到ID编号为"+id+"的资源");
                            return View(topic);
                        }
                        var blogintopic = new BlogsInTopic { blog = b, topic = ntopic, BlogOrder=i++ };
                        db.BlogsInTopics.Add(blogintopic);
                    }
                    if (topic.TopicImage != null)
                    {   //ValidateFileAttribute里已经检查过了
                        ntopic.isLocalImg = true;
                        string filename = BlogUtil.saveImage(topic.TopicImage);
                        ntopic.ImagePath = filename;
                        BlogUtil.savethumb(filename);
                    }
                    else
                    {
                        string imgname = BlogUtil.getFirstImg(ntopic.Content);
                        if (imgname == null || imgname.Length < 5)
                        {
                            ModelState.AddModelError("", "请添加预览图！（上传或在文中外链图片）");
                            return View(topic);
                        }
                        ntopic.isLocalImg = false;
                        ntopic.ImagePath = imgname;
                    }
                    db.SaveChanges();
                    ExpUtil.addExpOnPass(User.Identity.Name, HttpContext.Application["ExpAddOnPass"]);
                }
                catch
                {
                    if (ntopic.isLocalImg)
                        BlogUtil.removeFiles(new string[] {ntopic.ImagePath}, true);
                    throw;
                }
                return RedirectToAction("Details", new { id = ntopic.TopicID });
            }
            return View(topic);
        }

        //
        // GET: /Topic/Edit/5
        [Authorize(Roles = "Writers,Administrator,Moderator")]
        public ActionResult Edit(int id = 0)
        {
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            ViewBag.id = id;
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", topic.CategoryID);
            return View(new TopicEdit(topic));
        }

        //
        // POST: /Topic/Edit/5

        [HttpPost]
        [Authorize(Roles = "Writers,Administrator,Moderator")]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(int id, TopicEdit etopic)
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", etopic.CategoryID);
            int ret = BlogUtil.CheckBlogTag(etopic.TagName, 1);
            if (ret != 0)
            {
                ModelState.AddModelError("", ret > 0 ? "专题标签只能有1个" : "标签不得超过20个字符");
            }
            else if (!BlogUtil.checkContentTags(etopic.Content))
            {
                ModelState.AddModelError("", "不许内嵌代码！");
            }
            else if (ModelState.IsValid)
            {
                var topic = db.Topics.Find(id);
                bool uploadsaved = false;
                var blogcurrent = db.BlogsInTopics.Where(bi => bi.TopicID == id);
                foreach (var blog in blogcurrent)
                    db.BlogsInTopics.Remove(blog);
                int i = 0;
                foreach (var bid in etopic.blogIDs)
                {
                    Blog b = db.Blogs.Find(bid);
                    if (b == null)
                    {
                        ModelState.AddModelError("", "未找到ID编号为" + id + "的资源");
                        return View(topic);
                    }
                    BlogsInTopic bit = new BlogsInTopic { blog = b, topic = topic, BlogOrder = i++ };
                    db.BlogsInTopics.Add(bit);
                }

                if (topic.tag.TagName != etopic.TagName)
                {
                    var tag = db.Tags.SingleOrDefault(t => t.TagName == etopic.TagName);
                    if (tag == null)
                    {
                        tag = new Tag { TagName = etopic.TagName };
                    }
                    topic.tag = tag;
                }
                try
                {
                    if (etopic.TopicImage != null)
                    {
                        if (topic.isLocalImg)
                        {
                            BlogUtil.removeFiles(new string[] { topic.ImagePath }, true);
                        }
                        topic.isLocalImg = true;
                        string filename = BlogUtil.saveImage(etopic.TopicImage);
                        topic.ImagePath = filename;
                        BlogUtil.savethumb(filename);
                        uploadsaved = true;
                    }
                    else if (!topic.isLocalImg)
                    {
                        string imgname = BlogUtil.getFirstImg(etopic.Content);
                        if (imgname == null || imgname.Length < 5)
                        {

MyWebSite/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyMVCWeb.Controllers
{
    public class UploadController : Controller
    {
        //
        // GET: /Image/
        [OutputCache(Duration=864000,VaryByParam="img", Location=System.Web.UI.OutputCacheLocation.Client)]
        public ActionResult Index(string img)
        {
            if (string.IsNullOrEmpty(img))
                return HttpNotFound();
            string path = Server.MapPath("~/Images/upload/");
            if (!System.IO.File.Exists(path + img))
                return HttpNotFound();
            if (Request.UrlReferrer == null || Request.UrlReferrer.Host.Equals(Request.Url.Host, StringComparison.OrdinalIgnoreCase))
            {
                return File(path + img, "image/jpeg");
            }
            else
            {
                path = Server.MapPath("~/Images/thumbs/");
                if (System.IO.File.Exists(path + img))
                {
                    return File(path + img, "image/jpeg");
                }
                using(var bmp = new Bitmap(200, 50)){
                    var g = Graphics.FromImage(bmp);

                    g.FillRectangle(Brushes.White, 0, 0, 200, 50);
                    g.DrawString("流量有限，请勿盗链", new Font("Arial", 12), Brushes.Red, new PointF(0, 0));
                    using(var bmpstream = new System.IO.MemoryStream()){
                        bmp.Save(bmpstream, System.Drawing.Imaging.ImageFormat.Jpeg);
                        return File(bmpstream, "image/jpeg");
                    }
                }
            }
        }

    }
}

MyWebSite/Views/Topic/Details.cshtml
@model MyMVCWeb.Models.TopicDisplay

@{
    Topic topic = Model.topic;
    ViewBag.Title = topic.TopicTitle;
    ViewBag.Description = BlogUtil.getFirstLine(Model.topic.Content, 100, true);
    string picurl;
    if (topic.isLocalImg)
    {
        picurl = "http://" + HttpContext.Current.Request.Url.Host + "/Images/thumbs/" + topic.ImagePath;
    }
    else
    {
        picurl = BlogUtil.firstImgPath(topic.ImagePath);
    }
}

@section featured
{
@*
    <style>
        .post img
        {
            -moz-transition: width .5s,height .5s;
            -o-transition: width .5s,height .5s;
            -webkit-transition: width .5s,height .5s;
            transition: width .5s,height .5s;
        }
    </style>*@
<div id="blog" class="detaillayout">
            <h2>@topic.TopicTitle</h2>
            <br />
                <i class="icon-list"></i> 分类：<a class="badge badge-info" href="@Url.Action("List", "Topic", new { id = topic.CategoryID })">@BlogUtil.categoryName(topic.CategoryID)</a>
            <hr />
            <span style="font-size:small"><a href="@Url.Action("UserInfo", "Home", new { name = topic.Author })"><i class="icon-user"></i>@topic.Author</a> 于 @topic.CreateDate 发布，最后更新于 @topic.UpdateDate
                &nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-eye-open"></i> <span style="color: #808080">@(topic.TopicVisit)</span> 次浏览&nbsp;&nbsp;&nbsp;&nbsp;
                @if (User.Identity.IsAuthenticated)
                {<a href="#rptModal" class="btn btn-small" style="margin-bottom: 5px" onclick="rptTopic()" data-toggle="modal">汇报问题</a> <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>}
                @if (User.Identity.IsAuthenticated && (User.Identity.Name == topic.Author || Roles.IsUserInRole("Administrator") || Roles.IsUserInRole("Moderator")))
                {
                    @Html.ActionLink("编辑", "Edit", new { id = topic.TopicID });
                    <a id="dellink" onclick="delclick('@topic.TopicID');">删除</a>
                }
                
            </span><hr />
            @if (topic.isLocalImg)
            {
                <div id="imgdiv0">
            <a style="text-decoration:none;" href="@Url.Action("Index","Upload", new { img = MyMVCWeb.Models.BlogUtil.firstImgPath(topic.ImagePath)})" rel="lightbox[g]">
                <img class="uimg" src="@Url.Action("Index","Upload", new { img = MyMVCWeb.Models.BlogUtil.firstImgPath(topic.ImagePath)}) " alt="@topic.TopicTitle" />
            </a>
            <br /><br /></div>
            }
            <div id="blogcontent" style="width:100%;overflow:hidden;">
                    @Html.Raw(topic.Content)
            </div>
            <br />
            <div class="accordion" id="accordion2">
            @foreach (var blog in Model.blogs)
            {
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse@(blog.BlogID)">
                        @blog.BlogTitle @*<span class="btn btn-right" style="float:right">展开/折叠</span>*@
                        </a>
                    </div>
                    <div id="collapse@(blog.BlogID)" class="accordion-body collapse">
                        <div class="accordion-inner" style="border: 1px solid #ccc;border-radius: 1em">
                            <div class="post">
                                @{string imgpath = blog.isLocalImg ? Url.Action("Index","Upload", new { img = MyMVCWeb.Models.BlogUtil.firstImgPath(blog.ImagePath)}) : blog.ImagePath;}
                                <a href="@imgpath" style="text-decoration:none;" rel="lightbox[g]">
                                <img src="/images/loading.gif" data-src="@imgpath" alt="@blog.BlogTitle" style="max-height:300px;max-width:400px;"/></a> 
                            </div>
                        <br />
                        <p> @Html.Raw(BlogUtil.getFirstLine(blog.Content, 100))</p><br /> 
                        <a target="_blank" href="@Url.Action("Details", "Blog", new { id=blog.BlogID })" class="btn btn-primary">详细</a>
                        </div>
                    </div>
                </div>
            }
            </div>
    <div>
        <i class="icon-tags"></i><span> 专题标签：</span>
            <a class="label label-info" href="@Url.Action("Tags", "Search", new { id = topic.tag.TagID })">@(topic.tag.TagName)</a>
    </div>
        <!-- JiaThis Button BEGIN -->
    <div class="jiathis_style" style="margin-top:1em;">
	    <span class="jiathis_txt">分享到：</span>
	    <a class="jiathis_button_tools_1"></a>
	    <a class="jiathis_button_tools_2"></a>
	    <a class="jiathis_button_tools_3"></a>
	    <a class="jiathis_button_tools_4"></a>
	    <a rel="nofollow" href="http://www.jiathis.com/share?uid=1826445" class="jiathis jiathis_txt jiathis_separator jtico jtico_jiathis" target="_blank">更多</a>
	    <a class="jiathis_counter_style"></a>
    </div>
    <script type="text/javascript">
        var jiathis_config = { data_track_clickback: 'true', pic: '@picurl' };
    </script>
    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1347077965629870" charset="utf-8"></script>
    <!-- JiaThis Button END -->
    <script type="text/javascript" id="wumiiRelatedItems"></script>
</div>
}
<hr />

@Html.Action("Index","Advertisment")

<div id="replydiv">
@if (topic.Posts.Count > 0)
{
        @Html.Action("ShowReply","Reply", new { itemid = topic.TopicID, idtype = "2" })  
}
else
{
    <h3>暂无评论。</h3>
}
</div>
<div style="border-style: groove; border-color:chocolate; border-width: medium; border-radius:5px; width:100%; padding:5px; margin-top:1.2em;">
@if (Request.IsAuthenticated)
{
    <table border="1" style="width:100%; margin-left: .25em;">
        <colgroup>
            <col span="1" style="width: 100px;"/>
            <col span="1" />
        </colgroup>
        <tr>
            <td rowspan="2" style="vertical-align:top;text-align:center;"><img src="@Url.Action("Show", "Avatar")" style="max-height:100px;max-width:100px;" /></td>
            <td style="text-align:left">添加回复：</td>
        </tr>
        <tr>
            <td id="addreply_container" >
                @(Html.Partial("AddReply"))
            </td>
        </tr>
    </table>
    <div id="rptModal" class="modal hide fade" tabindex="-1" role="dialog" style="background-color:white;">
    @using (Html.BeginForm("Report", "Topic", FormMethod.Post, new { style = "margin:0;" }))
    {
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3>汇报问题</h3>
        </div>
        <div class="modal-body">
            <h3>原因：</h3>
        <textarea name="MsgContent" id="MsgContent" style="width:95%;height:160px;resize:none;"></textarea>
        </div><div class="modal-footer">
        <button class="btn" data-dismiss="modal">关闭</button>
        <input type="submit" value="汇报" class="btn btn-inverse" style="margin:0;"/>
        <input type="hidden" name="topicid" id="rpttopicid" value="@Model.topic.TopicID"/>
        <input type="hidden" name="postid" id="rptpostid"/>
            <input type="hidden" name="pagenum" id="pagenum" value="" />
        </div>
    }
    </div>
}
else
{
    <b>请登录后发表评论</b>
    @Html.ActionLink("注册", "Register", "Account", routeValues: new { returnUrl = Request.Url.AbsolutePath }, htmlAttributes: new { @class = "btn" })
    @Html.ActionLink("登录", "Login", "Account", routeValues: new { returnUrl = Request.Url.AbsolutePath }, htmlAttributes: new { @class = "btn" })
    
}
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryui")
}
@section end_scripts{
    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/detailScripts.js"></script>
    <script src="~/Scripts/lightbox-2.6.min.js"></script>
    <link href="~/Content/lightbox.css" rel="stylesheet" />
    <script src="~/Scripts/Expansion.js"></script>
    <script src="~/Scripts/jquery.unveil.min.js"></script>
    <script>
        var map = {};
        var last;
        function delclick(id) {
            if (confirm("确认删除？")) {
                $.post('@Url.Action("Delete")', { id: id }, redir);
            }
        }
        function redir() {
            window.location = "@Url.Action("List", "Topic", new { id = "" })";
        }
        $(function () {
            $('#lightbox').draggable();
            $('#blogcontent .label').hover(function () {
                selectText(this);
            });
            $('.post img').unveil();
            @*$('.accordion-toggle').click(function (event) {
                //event.preventDefault();
                var href = $(this).attr('href');
                var div = $(href);
                var ele = div.find('a[rel="lightbox[g]"]');
                ele.children('img').attr('src', ele.attr('href')).load(function () {
                    var img = new Image();
                    img.src = this.src;
                    if (img.height > 300) {
                        img.width = 300 / img.height * img.width;
                        img.height = 300;
                    }
                    if (img.width > 400) {
                        img.height = 400 / img.width * img.height;
                        img.width = 400;
                    }
                        $(this).css('width', img.width);
                        $(this).css('height', img.height);
                    }).error(function () {
                        //div.collapse('show');
                    });
                //if (last)
                //    last.collapse('hide');
                //last = div;
                //if (map[href]) {
                //    div.collapse('toggle');
                //}
                //else {
                //    var ele = div.find('a[rel="lightbox[g]"]');
                //    ele.children('img').attr('src', ele.attr('href')).load(function () {
                //        div.collapse('show');
                //    }).error(function () {
                //        div.collapse('show');
                //    });
                //    map[href] = true;
                //}
            });*@
        });
    </script>
    @if (User.Identity.IsAuthenticated)
    {
    <script>
        var replyeditor;
        function replaceeditor() {
            replyeditor = CKEDITOR.replace('addreplycontent', {
                toolbar: [
                                    ['Bold', 'Italic', '-', 'NumberedList', 'BulletedList', '-', 'Link', 'Unlink', ], ['Custom_Smiley', 'Image'],
                                    ['TextColor', 'BGColor', 'Styles']], uiColor: '#019ed5'
            });
        }
        $(function () {
            replaceeditor();
        });
        $('#SubmitReply').button({ 'loading-text': "提交中" });
        
        function delreply(id) {
            if (confirm("确认删除？")) {
                $.post('@Url.Action("DeletePost", "Reply")', { PostId: id }, partial(hidepost, id));
            }
        }
	function delPostReply(id) {
            if (confirm("确认删除？")) {
                $.post('@Url.Action("DeleteReply", "Reply")', { ReplyId: id }, partial(hidereply, id));
            }
        }
        function redirectpost(result) {
            if (result.redirect) {
                window.location.href = '@Request.RawUrl' + result.redirect;
                window.location.reload();
            }
            else {
                $('#addreply_container').html(result);
            }
        }
        var btnclicked = false;
        function submitreply() {
            var data = replyeditor.getData();
            var captcha = $('input[name="Captcha"]').val();
            var prefix = $('input[name="Prefix"]').val();
            if (btnclicked || data == '')
                return false;
            btnclicked = true;
            $('#SubmitReply').button("loading");
            $("#loading").show();
            $.post('@Url.Action("AddReply", "Reply")', { itemid: '@topic.TopicID', addreplycontent: data, Captcha: captcha, Prefix: prefix, idtype:2 },
                redirectpost).complete(oncomplete);
        }
        function oncomplete() {
            btnclicked = false;
            $('#SubmitReply').button("reset");
            $("#loading").hide();
            replaceeditor();
        }

        function rptReply(id) {
            $("#rptpostid").val(id);
            $("#pagenum").val($("#curpagenum").val());
        }
        function rptTopic() {
            $("#rptpostid").val(null);
        }

        function replyPost(postid) {

        }
    </script>
   
    }

    <script type="text/javascript">
        var wumiiPermaLink = "@Request.Url.GetLeftPart(UriPartial.Path)"; 
        var wumiiTitle = "@topic.TopicTitle"; 
        var wumiiTags = "@topic.tag.TagName"; 
        var wumiiCategories = ["@BlogUtil.categoryName(topic.CategoryID)"]; 
        var wumiiSitePrefix = "http://gmgard.us/";
        var wumiiParams = "&num=5&mode=2&pf=JAVASCRIPT";
    </script>
    <script type="text/javascript" src="http://widget.wumii.cn/ext/relatedItemsWidget"></script>
    <a rel="nofollow" href="http://www.wumii.com/widget/relatedItems" style="border:0;">
        <img src="http://static.wumii.cn/images/pixel.png" alt="无觅相关文章插件，快速提升流量" style="border:0;padding:0;margin:0;" />
    </a>
}

MyWebSite/Views/Topic/ShowReply.cshtml
@model PagedList.IPagedList<MyMVCWeb.Models.TopicPost>
<input type="hidden" id="curpagenum" value="@Model.PageNumber"/>
@foreach(var post in Model)
{
    int index = 0;
    <table style="width:100%" id ="@("listpost"+post.PostID)" class="replytable">
                <colgroup>
                   <col span="1" style="width: 100px;"/>
                   <col span="1" />
                </colgroup>
                <tr>
                    <td rowspan="3" class="replyavatar"><a href="@Url.Action("UserInfo","Home",new {name = post.Author})"><img src="@Url.Action("Show","Avatar",new {name = post.Author})" style="max-height:100px;max-width:100px;" /></a></td>
                    <td style="text-align:left; padding-left:2em;">@Html.ActionLink(post.Author, "UserInfo","Home",new {name = post.Author},null) 发表于 @post.PostDate
                        &nbsp;
                        @if (User.Identity.IsAuthenticated && post.topic.TopicID > 0)
                        {
                            <a onclick="rptReply(@post.PostID);" data-toggle="modal" role="button" href="#rptModal" class="hovershow">举报</a>
                        }
                        &nbsp;
                        @if(User.IsInRole("Administrator") || User.IsInRole("Moderator") || User.Identity.Name == post.Author)
                        {
                            <a onclick="editreply(@post.PostID);" class="hovershow">编辑</a>@Html.Raw("  ")
                            <a onclick="delreply(@post.PostID);" class="hovershow">删除</a>
                        }
                    </td>
                </tr>
                <tr>
                    <td style="padding-left:2em;"><div id='@("postcontent"+ post.PostID)' class="bubble"><div class="reply">@Html.Raw(post.Content)</div></div></td>
                </tr>
                <tr>
                    <td style="padding-left:2em;display:none;" id="btnarea_@post.PostID">
                        @if(User.IsInRole("Administrator") || User.IsInRole("Moderator") || User.Identity.Name == post.Author)
                        {
                            <input type="button" id="editreplybtn_@post.PostID" value ="提交" class="btn btn-small" onclick="@string.Format("editclick({0},'{1}');", post.PostID, Url.Action("EditReply")) " >
                            @Html.Raw(" ")
                            <input type="button" id="canceleditbtn_@post.PostID" value ="取消" class="btn btn-small" onclick="cancelclick();">
                            <span class = "field-validation-error" id ="editerror_@post.PostID"></span>
                        }
                    </td>
                </tr>
            </table>
    index++;
}
@if (!Model.IsFirstPage || !Model.IsLastPage)
{
    Html.RenderPartial("_AjaxPager", Model);
}
<script>
    if (location.hash && location.hash.indexOf("listpost") != -1) {
        $(location.hash).css("background-color", "lightGrey");
    }
</script>