MyWebSite/Controllers/AvatarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MyMVCWeb.Models;
using System.Web.Routing;

namespace MyMVCWeb.Controllers
{
    public class AvatarController : Controller
    {
        private UsersContext db = new UsersContext();

        const string defaultavatar = "~/Images/金馆长.jpg";
        //
        // GET: /Avatar/Show/name
        public ActionResult Show(string name=null)
        {
            var pics = db.Avatars;
            if (name == null)
            {
                MembershipUser user = Membership.GetUser();
                if (user != null)
                {

                    try
                    {
                        Pictures PicData = pics.Where(p => p.PicName == user.UserName).First();
                        return File(PicData.Data, PicData.PicType);
                    }
                    catch
                    {
                        return File(Server.MapPath(defaultavatar), "image/jpeg");
                    }

                }
                else
                {
                    return File(Server.MapPath(defaultavatar), "image/jpeg");
                    //Response.Redirect("~/Default.aspx");
                }

            }
            else
            {
                Pictures PicData = pics.FirstOrDefault(p => p.PicName == name);
                if (PicData != null)
                {
                    return File(PicData.Data, PicData.PicType);
                }
                else
                {
                    return File(Server.MapPath(defaultavatar), "image/jpeg");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyWebSite/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using MyMVCWeb.Models;
using PagedList;

namespace MyMVCWeb.Controllers
{
    public class BlogController : Controller
    {
        public BlogController():base()
        {
            object size = System.Web.HttpContext.Current.Application["ListPagesize"];
            if (size is int)
                listpagesize = (int)size;
            else
                listpagesize = _listpagesize;
            
        }
        private BlogContext db = new BlogContext();

        private const int _listpagesize = 18;

        private int listpagesize;
        
        //
        // GET: /BlogList/

        public ActionResult List(int? id, int page=1, string sort="")
        {
            int pagesize = listpagesize;
            IQueryable<Blog> query = db.Blogs.Where(b => b.isApproved == true);
            if (id.HasValue && id.Value > 0)
            {
                if (db.Categories.Find(id.Value) == null)
                    return HttpNotFound();
                query = query.Where(b => b.CategoryID == id);
            }
            ViewBag.DateSortParm = String.IsNullOrEmpty(sort) ? "Date" : "";
            ViewBag.VisitSortParm = sort == "Visit_desc" ? "Visit" : "Visit_desc";
            ViewBag.PostSortParm = sort == "Post_desc" ? "Post" : "Post_desc";
            ViewBag.RateSortParm = sort == "Rate_desc" ? "Rate" : "Rate_desc";
            ViewBag.CurrentSort = sort;
            var model = BlogUtil.getSortedQuery(db, query, sort);
            
            int pagecount = (int)Math.Ceiling( (double) query.Count() / pagesize);
            int pagenumber;
            if (page > 0 && page <= pagecount)
            {
                pagenumber = page;
            }
            else{
                pagenumber = 1;
            }
            return View("List",model.ToPagedList(pagenumber,pagesize));
        }
        [Authorize]
        public ActionResult Create()
        {
            SelectList sl = new SelectList(db.Categories.ToList(), "CategoryID", "CategoryName");
            ViewBag.CategoryList = sl;
            return View();
        }


        [HttpPost][Authorize]
        [ValidateAntiForgeryToken][ValidateInput(false)]
        public ActionResult Create(BlogEdit blog, HttpPostedFileBase[] files, string Captcha, string Prefix)
        {
            SelectList sl = new SelectList(db.Categories.ToList(), "CategoryID", "CategoryName");
            ViewBag.CategoryList = sl;
            string content = blog.Content;
            if (BlogUtil.checkCaptchaError(Captcha, Prefix))
            {
                ModelState.AddModelError("Captcha", "验证码计算错误，请重试。");
                return View(blog);
            }
            if (content == null || string.IsNullOrWhiteSpace(BlogUtil.removeAllTags(content)))
            {
                ModelState.AddModelError("", "内容不能为空或纯图片");
                return View(blog);
            }
            if (blog.CategoryID != 1)
            {
                if (blog.BlogLinks == null)
                {
                    ModelState.AddModelError("", "链接地址不能为空");
                    return View(blog);
                }
                else
                {
                    blog.BlogLinks = blog.BlogLinks.Where(b => !string.IsNullOrWhiteSpace(b.url)).ToArray();
                    if (!BlogUtil.checkBlogLinks(blog.BlogLinks))
                    {
                        ModelState.AddModelError("", "链接地址不能为空，且不得包含javascript");
                        return View(blog);
                    }
                }
            }
            if (!BlogUtil.checkContentTags(content))
            {
                ModelState.AddModelError("", "不许内嵌代码！警察叔叔就是这个人！！！！");
                return View(blog);
            }
            int ret = BlogUtil.CheckBlogTag(blog.BlogTags);
            if (ret != 0)
            {
                ModelState.AddModelError("", ret > 0 ? "标签不得超过10个" : "标签不得超过20个字符");
                return View(blog);
            }
            content = BlogUtil.appendPassToContent(content, blog.BlogPasswords);
            string imgname = null;
            List<string> imglist = null;
            List<HttpPostedFileBase> BlogImages = null;
            bool isLocalimg = false;
            if (files != null)
            {
                int i = 0;
                BlogImages = files.ToList();
                foreach (var file in files)
                {
                    if (file != null)
                    {
                        if (!file.ContentType.Contains("image"))
                        {
                            ModelState.AddModelError("", "不接受的文件类型");
                            return View(blog);
                        }
                        else if (file.ContentLength > 1048576 * 4)
                        {
                            ModelState.AddModelError("", "文件不得超过4MB");
                            return View(blog);
                        }
                        isLocalimg = true;
                        i++;
                    }
                    else
                    {
                        BlogImages.Remove(file);
                        content = BlogUtil.removeImgPlaceholder(content, i);
                    }
                }
            }
            int addSuccess;
            try
            {
                if (!isLocalimg)
                {
                    imgname = BlogUtil.getFirstImg(content);
                    if (imgname == null || imgname.Length < 5)
                    {
                        ModelState.AddModelError("", "请添加预览图！（上传或在文中外链图片）");
                        return View(blog);
                    }
                }
                else
                {
                    imglist = BlogUtil.saveImages(BlogImages);
                    imgname = imglist.First();
                    BlogUtil.savethumb(imgname);
                    imglist.Remove(imgname);
                }
                // Add product data to DB.
                string imgpath = imgname;
                if (imglist != null)
                {
                    foreach (string name in imglist)
                    {
                        imgpath += (";" + name);
                    }
                }
                bool approve = false;
            
                if (User.IsInRole("Administrator") || User.IsInRole("Writers") || User.IsInRole("Moderator"))
                {
                    approve = true;
                    ExpUtil.addExpOnPass(User.Identity.Name, HttpContext.Application["ExpAddOnPass"]);
                }
                addSuccess = BlogUtil.AddBlog(blog.BlogTitle, content,
                    blog.CategoryID, imgpath, User.Identity.Name, approve, isLocalimg, blog.BlogLinks);
                if (!string.IsNullOrEmpty(blog.BlogTags))
                {
                    string[] tags = BlogUtil.SplitTags(blog.BlogTags);
                    BlogUtil.AddTagsForBlog(addSuccess, tags);
                }
            }
            catch 
            {
                if (isLocalimg)
                {
                    imglist.Insert(0, imgname);
                    BlogUtil.removeFiles(imglist, true);
                }
                throw;
            }
            return RedirectToAction("Details", new { id = addSuccess });
        }

        public ActionResult Details(int id=0)
        {
            Blog blog = null;
            if(id > 0)
                blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return RedirectToAction("List");
            }
            blog.BlogVisit++;
            db.SaveChanges();
            BlogDisplay bd = new BlogDisplay();
            bd.blog = blog;
            bd.tag = db.TagsInBlogs.Where(i => i.BlogID == id).Select(i => i.tag);
            foreach (var tag in bd.tag)
            {
                tag.TagVisit++;
            }
            db.SaveChanges();
            return View(bd);
        }

        [HttpGet]
        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Delete(int id, bool sendmsg, string MsgContent)
        {
            Blog b = db.Blogs.Find(id);
            if(sendmsg){
                BlogUtil.SendNoticeMsg(b.Author, NoticeType.delblog,User.Identity.Name, MsgContent, b.BlogTitle);
            }
            BlogUtil.deleteBlog(id);
            return RedirectToAction("List");
        }
        
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int? blogid)
        {
            if (blogid.HasValue)
            {
                Blog b = db.Blogs.Find(blogid.Value);
                if (b != null)
                {
                    if (b.Author == User.Identity.Name || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
                    {
                        BlogUtil.deleteBlog(b.BlogID);
                        return RedirectToAction("List");
                    }
                }
            }
            HttpContext.Response.StatusCode = 403;
            HttpContext.Response.End();
            return null;
            //throw new InvalidOperationException("Invalid Blog ID, or authorize error.");
        }
        [Authorize]
        public ActionResult Edit(int? id)
        {
            Blog blog = null;
            if (id.HasValue)
                blog = db.Blogs.Find(id.Value);
            SelectList sl = new SelectList(db.Categories.ToList(), "CategoryID", "CategoryName", blog.CategoryID);
            ViewBag.CategoryList = sl;
            if (blog == null)
            {
                return HttpNotFound();
            }
            if (blog.Author != User.Identity.Name && !User.IsInRole("Administrator") && !User.IsInRole("Moderator"))
            {
                return RedirectToAction("Details", new { id = id });
            }

MyWebSite/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyMVCWeb.Controllers
{
    public class UploadController : Controller
    {
        //
        // GET: /Image/
        [OutputCache(Duration=864000,VaryByParam="img", Location=System.Web.UI.OutputCacheLocation.Client)]
        public ActionResult Index(string img)
        {
            if (string.IsNullOrEmpty(img))
                return HttpNotFound();
            string path = Server.MapPath("~/Images/upload/");
            if (!System.IO.File.Exists(path + img))
                return HttpNotFound();
            if (Request.UrlReferrer == null || Request.UrlReferrer.Host.Equals(Request.Url.Host, StringComparison.OrdinalIgnoreCase))
            {
                return File(path + img, "image/jpeg");
            }
            else
            {
                path = Server.MapPath("~/Images/thumbs/");
                if (System.IO.File.Exists(path + img))
                {
                    return File(path + img, "image/jpeg");
                }
                using(var bmp = new Bitmap(200, 50)){
                    var g = Graphics.FromImage(bmp);

                    g.FillRectangle(Brushes.White, 0, 0, 200, 50);
                    g.DrawString("流量有限，请勿盗链", new Font("Arial", 12), Brushes.Red, new PointF(0, 0));
                    using(var bmpstream = new System.IO.MemoryStream()){
                        bmp.Save(bmpstream, System.Drawing.Imaging.ImageFormat.Jpeg);
                        return File(bmpstream, "image/jpeg");
                    }
                }
            }
        }

    }
}

MyWebSite/Views/Blog/BlogLinkPartial.cshtml
@model MyMVCWeb.Models.BlogLink[]

@{int i = 0;}
<style>
    .btfile{position:absolute;right:30px;background:url('/Images/upload.jpg') center no-repeat}
    .btfile input{width:68px;opacity:0;padding:0;margin:0}
</style>
<div style="position:relative">
    <div class="btfile">
        <input type="file" id="btfile" title="上传bt种子" />
    </div>
<table>
    <thead>
        <tr><th>显示名称</th><th>链接地址</th></tr>
    </thead>
<tbody id="TextBoxesGroup">
    <tr>
        <td colspan="2"><a id="addButton"><i class="icon-plus-sign"></i></a><a id="removeButton"><i class="icon-minus-sign"></i></a></td>
    </tr>
    @if(Model !=null && Model.Length > 0){
        for (; i < Model.Length; i++ )
        {
            <tr id="TextBoxRow@(i)">
                <td><input type="text" name="BlogLinks[@i].name"placeholder="选填" value="@Model[i].name" /></td>
        <td><input type="text" name="BlogLinks[@i].url" value="@Model[i].url"/>
        </td>
            </tr>
        }

    }
    else{
    <tr>
        <td><input type="text" name="BlogLinks[0].name"placeholder="选填" /></td>
        <td><input type="text" name="BlogLinks[0].url" id="BlogLinks_url" />
        </td>
    </tr>
    }
</tbody>
</table>
</div>
<script>
    var counter = 1 + @(i>0 ? i-1 : 0) ;
    var debugresult;
    $(function () {
        if (counter == 1)
            $("#removeButton i").addClass("icon-white");

        $("#addButton").click(function () {
            addRow("","");
        });
        function addRow(name,url){
            var newTextBoxRow = $(document.createElement('tr'))
                 .attr("id", 'TextBoxRow' + counter);
            newTextBoxRow.append('<td>' +
                  '<input type="text" name="BlogLinks[' + counter + '].name" value="'+name+'" >' +
                  '</td><td>' +
                  '<input type="text" name="BlogLinks[' + counter + '].url" value="'+url+'" ></td>'
                  );
            newTextBoxRow.appendTo("#TextBoxesGroup");
            if (counter == 1)
                $("#removeButton i").removeClass("icon-white");
            counter++;

            $('input[name^="BlogLinks"][name$="url"]').change(autofillname);
        }

        $("#removeButton").click(function () {
            if (counter == 1) {
                return false;
            }
            counter--;
            $("#TextBoxRow" + counter).remove();
            if (counter == 1)
                $("#removeButton i").addClass("icon-white");
        });

        $('#btfile').change(function (event) {
            var file = $(this).val();
            if(file){
                var size = this.files[0].size;
                if(size > 524288 * 2){
                    alert("文件不得超过1MB");
                }
                else{
                    var reader = new FileReader();
                    reader.onloadend = function () {
                        $.post('@Url.Action("GetMagnet")',{ data: reader.result.split(',')[1]}, getMagnet, "text");
                    };
                    reader.readAsDataURL(this.files[0]);
                }
            }
            $(this).val('');
        });
        $('input[name^="BlogLinks"][name$="url"]').change(autofillname);
        function autofillname() {
            var input = $(this).val();
            var name = $(this).parent().parent().find('input[name$="name"]');
            if(input && !name.val()){
                if(input.indexOf("magnet") >= 0){
                    name.val('磁力链');
                }
                else if(input.indexOf("baidu") >= 0){
                    name.val('度娘');
                }
                else if(input.indexOf("jbpan") >= 0){
                    name.val('菊爆盘');
                }
                else if(input.indexOf("xunlei") >= 0){
                    name.val('快船');
                }
                else if(input.indexOf("howfile") >= 0){
                    name.val('好盘');
                }
                else if(input.indexOf("yunpan") >= 0){
                    name.val('360盘');
                }
            }
        }
        function getMagnet(result){
            if(!result){
                alert("无效的种子文件！");
            }
            result = JSON.parse(result);
            debugresult = result;
            var inputs = $('input[name^="BlogLinks"][name$="url"]');
            var added = false;
            for(var i=0;i<inputs.length;i++){
                if(!inputs[i].value){
                    inputs[i].value = result;
                    $('input[name^="BlogLinks"][name$="name"]')[i].value = "磁力链";
                    added=true;
                    break;
                }
            }
            if(!added){
                addRow("磁力链",result);
            }
        }
    });
</script>

MyWebSite/Views/Blog/Edit.cshtml
@model MyMVCWeb.Models.BlogEdit

@{
    ViewBag.Title = "文章编辑";
    int id = ViewBag.id;
}

@section featured{

<h2>编辑模式</h2>
<hr />
    @Html.ValidationSummary()
@using (Html.BeginForm("Edit", "Blog", new { id = id }, FormMethod.Post, new {id="editform", enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<Label for="CategoryID">类别：</Label>
@Html.DropDownListFor(m => m.CategoryID, ViewBag.CategoryList as SelectList)
<Label for="BlogTitle">标题：</Label>
@Html.TextBoxFor(m => m.BlogTitle, new { maxlength = 80, @class="input-block-level" })

    <br />
    if (Model.islocalimg)
    {
    <div id="herodiv" class="editthumbs">
        <a class="del" title="删除" onclick="del(0);" ></a>
        <img id="heroimg" src="@Url.Action("Index","Upload", new { img = MyMVCWeb.Models.BlogUtil.firstImgPath(Model.ImagePath)})" alt="@Model.BlogTitle " style="max-height:300px;max-width:400px;" />
        <a class="ins" title="嵌入" onclick="insertAttach(0,false);"></a>
    </div><br />
    @Html.Raw(BlogUtil.getRestImgTags(Model.ImagePath, false))
    <br />
    }
<div id="upload_resizable" class="uploaddiv" style="overflow:hidden;position:relative;border:1px solid;display:inline-block;width:35em;margin:2em auto;white-space:nowrap;">
    <label class="uploadtext">添加预览图(最大4MB每张):</label>
    <hr />
    <div class="upinputdiv">
        <div class="upinput">
        <input type="file" id="file1" name="files" /><a class="hide" title="删除" onclick="removeup(0)"><i class="icon-remove-sign"></i></a> <a class="hide" style="top:25px;" title="嵌入文中" onclick="insertAttach(0 , true);"><i class="icon-picture"></i></a>
        </div>
        <div class="form-inline" style="display:inline-block;">
        <label class="checkbox"><input type="checkbox" class="CheckBox" id="checkbox1" name="checkbox1" value="true" />作为主预览图</label>
        </div><br />
    @for (int j = 2; j <= 4; j++)
    {
        <div class="upinput">
        <input type="file" id="file@(j)" tabindex="-1" name="files" /><a class="hide" title="删除" onclick="removeup(@(j-1))"><i class="icon-remove-sign"></i></a> <a class="hide" style="top:25px;" title="嵌入文中" onclick="insertAttach(@(j-1), true);"><i class="icon-picture"></i></a>
        </div><br />
    }
    </div>
</div>
    
    <input type="hidden" name="ImagePath" ID="HiddenField1"/>
    @Html.HiddenFor(m => m.islocalimg)
    <br />
    @Html.TextAreaFor(m => m.Content, new { @class="ckeditor", id ="EditBlogContent"})
    <br />
    <h3>追加密码</h3>
    @Html.Partial("BlogPassword",Model.BlogPasswords, new ViewDataDictionary())

    <h3>链接</h3>
    @Html.Partial("BlogLinkPartial",Model.BlogLinks, new ViewDataDictionary())

    <h3>标签</h3>

    @Html.EditorFor(m => m.BlogTags)

    <Label ID="Label1" class="validation-summary-errors"></Label>
    <br />
    <input type="submit" ID="SubmitButton" data-loading-text="提交中..." autocomplete="off" value="提交" OnClick="startsubmit(this.id);submitimgs();" class="btn btn-primary" />
    <img src="~/Images/Loading2.gif" id="loadinggif" style="display:none;"/>
    <input type="button" ID="Cancel" value="取消" OnClick="redir();" class="btn" />
    <br />

}

}

@section end_scripts{
    <script src="~/Scripts/Expansion.js"></script>
    <script src="~/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        var str = '@Model.ImagePath';
        var hasimg = '@(Model.islocalimg ? 1 : 0)';
        var imglist = hasimg == 1 ? str.split(";") : [];
        var basepath = '/Upload/';
        var imgcount = imglist.length;
        var linehigh = 52; var hidden;
        var isvalid = true;
        $(document).ready((function () {
            var resize = $("#upload_resizable");
            if (imgcount >= 0 && imgcount < 4) {
                resize.height((4 - imgcount + 1) * linehigh);
                if (imgcount == 0)
                    $("#checkbox1").attr('disabled', 'disabled');
            }
            else {
                resize.hide();
            }
            $('#editform').submit(function(){
                if($(this).valid() && isvalid){
                    $('#SubmitButton').button('loading');
                    $('#loadinggif').show();
                    submitimgs();
                }
            });
            $('input[name="files"]').change(function (event) {
                if (event.target.files) {
                    $(this).siblings('a').show();
                }
                else {
                    $(this).siblings('a').hide();
                }
                if (event.target.files && event.target.files[0].size >= 4096 * 1024) { // 4MB
                    $('#filemsg').show();
                    isvalid = false;
                }
                else {
                    $('#filemsg').hide();
                    isvalid = true;
                }
            });
            hidden = document.getElementById("HiddenField1");
        }));
        function removeup(id) {
            id++;
            var elem = $('#file' + id)
            elem.val('');
            elem.siblings('a').hide();
        }
        function set(pos) {
            var hero = document.getElementById('heroimg');
            var thumb = document.getElementById('thumb' + pos);
            var tmp = imglist[0];
            imglist[0] = imglist[pos];
            imglist[pos] = tmp;
            hero.setAttribute('src', basepath + imglist[0]);
            thumb.setAttribute('src', basepath + imglist[pos]);
            var editor = CKEDITOR.instances.EditBlogContent;
            var data = editor.getData();
            data = data.ReplaceAll("[img" + pos + "]", "[imgtmp]");
            data = data.ReplaceAll("[img0]", "[img" + pos + "]");
            editor.setData(data.ReplaceAll("[imgtmp]", "[img0]"));
            return false;
        }
        function del(pos) {
            //if (pos >= imgcount){
            //    return false;
            //}
            var editor = CKEDITOR.instances.EditBlogContent;
            var data = editor.getData();
            if(data.indexOf("[img" + pos + "]") >= 0 ){
                data = data.ReplaceAll("[img" + pos + "]", "");
                var i = pos;
                for (++i; i < 4; i++) {
                    data = data.ReplaceAll("[img" + i + "]", "[img" + (i - 1) + "]");
                }
                editor.setData(data.toString());
            }
            var resize = $("#upload_resizable");
            resize.show();
            if (imgcount == 1) {
                imglist = null;
                var thumb = document.getElementById('herodiv');
                thumb.style.display = 'none';
                imgcount = 0;
                $("#checkbox1").attr('disabled', 'disabled');
                resize.height((4 - imgcount + 1) * linehigh);
                return false;
            }
            if (pos == 0) {
                var a = 1;
                for (a = 1; a < imglist.length ; a++) {
                    if (imglist[a] != null)
                        break;
                }
                imglist[0] = imglist[a];
                var hero = document.getElementById('heroimg');
                hero.setAttribute('src', basepath + imglist[0]);
                pos = a;
            }
            imglist[pos] = null;
            $('#imgdiv' + pos).hide();
            imgcount--;
            resize.height((4 - imgcount + 1) * linehigh);
            return false;
        }
        function submitimgs() {
            var editor = CKEDITOR.instances.EditBlogContent;
            editor.setMode('wysiwyg');
            if (imglist) {
                if (imgcount == 0)
                    hidden.value = '';
                else {
                    var i = 0;
                    var b = Array();
                    for (i = 0; i < imglist.length; i++) {
                        if (imglist[i] != null)
                            b.push(imglist[i]);

                    }
                    hidden.value = b.join(';');
                }
            }
            else
                hidden.value = "";
        }
        function insertAttach(id, isnew) {
            var tag = isnew ? "nimg" : "img";
            if (isnew) {
                var upload = document.getElementById('file' + (id + 1));
                if (upload.value.length < 1)
                    return;
            }
            var editor = CKEDITOR.instances.EditBlogContent;
            editor.insertHtml('[' + tag + id + ']');
        }
        function redir(){
            window.location='@Url.Action("Details",new {id = id})';
        }
</script>
}

MyWebSite/Views/Blog/ShowReply.cshtml
@model PagedList.IPagedList<MyMVCWeb.Models.Post>
<input type="hidden" id="curpagenum" value="@Model.PageNumber"/>
@foreach(Post post in Model)
{
    int index = 0;
    <table style="width:100%" id ="@("listpost"+post.PostId)" class="replytable">
                <colgroup>
                   <col span="1" style="width: 100px;"/>
                   <col span="1" />
                </colgroup>
                <tr>
                    <td rowspan="3" class="replyavatar"><a href="@Url.Action("UserInfo","Home",new {name = post.Author})"><img src="@Url.Action("Show","Avatar",new {name = post.Author})" style="max-height:100px;max-width:100px;" /></a></td>
                    <td style="text-align:left; padding-left:2em;">@Html.ActionLink(post.Author, "UserInfo","Home",new {name = post.Author},null) 发表于 @post.PostDate
                        &nbsp;
                        @if (User.Identity.IsAuthenticated && post.blog.BlogID > 0)
                        {
                            <a onclick="rptReply(@post.PostId);" data-toggle="modal" role="button" href="#rptModal" class="hovershow">举报</a>
                        }
                        &nbsp;
                        @if(User.IsInRole("Administrator") || User.IsInRole("Moderator") || User.Identity.Name == post.Author)
                        {
                            <a onclick="editreply(@post.PostId);" class="hovershow">编辑</a>@Html.Raw("  ")
                            <a onclick="delreply(@post.PostId);" class="hovershow">删除</a>
                        }
                    </td>
                </tr>
                <tr>
                    <td style="padding-left:2em;"><div id='@("postcontent"+ post.PostId)' class="bubble"><div class="reply">@Html.Raw(post.Content)</div></div></td>
                </tr>
                <tr>
                    <td style="padding-left:2em;display:none;" id="btnarea_@post.PostId">
                        @if(User.IsInRole("Administrator") || User.IsInRole("Moderator") || User.Identity.Name == post.Author)
                        {
                            <input type="button" id="editreplybtn_@post.PostId" value ="提交" class="btn btn-small" onclick="@string.Format("editclick({0},'{1}');", post.PostId, Url.Action("EditReply")) " >
                            @Html.Raw(" ")
                            <input type="button" id="canceleditbtn_@post.PostId" value ="取消" class="btn btn-small" onclick="cancelclick();">
                            <span class = "field-validation-error" id ="editerror_@post.PostId"></span>
                        }
                    </td>
                </tr>
            </table>
    index++;
}
@if (!Model.IsFirstPage || !Model.IsLastPage)
{
    Html.RenderPartial("_AjaxPager", Model);
}
<script>
    if (location.hash && location.hash.indexOf("listpost") != -1) {
        $(location.hash).css("background-color", "lightGrey");
    }
</script>

MyWebSite/Views/Blog/_ListPartial.cshtml
@model MyMVCWeb.Models.BlogWithRating

        <li id="@Model.blog.BlogID">
            <div class="badge">
                评分：@Model.rating
            </div>
            <div class="icon">
                <div class="imgcenter">
                    @{string imgpath = Model.blog.isLocalImg ? ("/Images/Thumbs/" + MyMVCWeb.Models.BlogUtil.firstImgPath(Model.blog.ImagePath)) : Model.blog.ImagePath;}
                    <img src="@imgpath"/>
                </div>
            </div>
            <div class="data">
                <h4>
                    @Model.blog.BlogTitle
                </h4>
                <p style="word-break:keep-all"> @BlogUtil.getFirstLine(Model.blog.Content, 100, true)</p>
                <strong>投稿：@Model.blog.Author</strong>
                <br />
                &nbsp;<span class="lfoot"><i class="icon-eye-open ico"></i> @Model.blog.BlogVisit</span><span class="lfoot"><i class="icon-comment ico"></i> @Model.blog.posts.Count</span>
            </div>
        </li>