MyWebSite/Controllers/AdvertismentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyMVCWeb.Models;

namespace MyMVCWeb.Controllers
{
    public class AdvertismentController : Controller
    {
        [ChildActionOnly]
        public PartialViewResult Index()
        {
            List<Advertisment> ads;
            using (var db = new BlogContext())
            {
                var orderads = db.Advertisments.OrderByDescending(a => a.ClickCount);
                if (orderads.Count() > 0)
                {
                    db.Advertisments.First().ExposeCount++;
                    db.SaveChanges();
                    var ran = new Random();
                    ads = orderads.Take(3).ToList();
                    var restads = orderads.Skip(3).ToList();
                    ads.AddRange(restads.OrderBy(a => ran.Next()));
                }
                else
                    ads = null;
            }
            return PartialView("_AdPartial",ads);
        }
        public JsonResult Click(string adid)
        {
            int id;
            if (!int.TryParse(adid, out id))
                return null;
            else
            {
                using (var db = new BlogContext())
                {
                    var ad = db.Advertisments.Find(id);
                    if (ad != null)
                    {
                        ad.ClickCount++;
                        db.SaveChanges();
                        return Json(ad.ClickCount);
                    }
                    else
                        return null;
                }
            }
        }
        [Authorize(Roles = "Administrator"), HttpGet]
        public ViewResult AdManage()
        {
            using (var db = new BlogContext())
            {
                var ads = db.Advertisments.ToList();
                ViewBag.msg = TempData["msg"];
                return View(ads);
            }
        }
        [Authorize(Roles = "Administrator"), HttpPost, ValidateAntiForgeryToken]
        public RedirectToRouteResult AdManage(string AdID, string AdUrl, string AdImg, string AdTitle, string action)
        {
            using (var db = new BlogContext())
            {
                int id;
                Advertisment a;
                switch (action)
                {
                    case "new":
                        if (string.IsNullOrWhiteSpace(AdUrl))
                        {
                            TempData["msg"] = "请输入URL";
                        }
                        else
                        {
                            a = new Advertisment();
                            a.AdTitle = AdTitle;
                            a.AdUrl = AdUrl;
                            a.ImgUrl = AdImg;
                            db.Advertisments.Add(a);
                            db.SaveChanges();
                            TempData["msg"] = "添加成功";
                        }
                        break;
                    case "edit":
                        if (string.IsNullOrWhiteSpace(AdUrl))
                        {
                            TempData["msg"] = "请输入Url";
                        }
                        else if (int.TryParse(AdID, out id))
                        {
                            a = db.Advertisments.Find(id);
                            if (a != null)
                            {
                                a.AdTitle = AdTitle;
                                a.AdUrl = AdUrl;
                                a.ImgUrl = AdImg;
                                db.SaveChanges();
                                TempData["msg"] = "编辑成功";
                            }
                            else
                            {
                                TempData["msg"] = "未找到";
                            }
                        }
                        break;
                    case "del":
                        if (int.TryParse(AdID, out id))
                        {
                            a = db.Advertisments.Find(id);
                            if (a != null)
                            {
                                db.Advertisments.Remove(a);
                                db.SaveChanges();
                                TempData["msg"] = "删除成功";
                            }
                            else
                            {
                                TempData["msg"] = "未找到";
                            }
                        }
                        break;
                }

                return RedirectToAction("AdManage");
            }
        }
    }
}

MyWebSite/Views/Advertisment/AdManage.cshtml
@model IEnumerable<MyMVCWeb.Models.Advertisment>

@{
    ViewBag.Title = "广告管理";
}
<style>
    input[type='text']
    {
        width:90%;
    }
</style>
<h2>广告管理</h2>
@if(Model.Count() > 0){
<h4>展示次数：@Model.First().ExposeCount</h4>
}
<p class="text-warning">@ViewBag.msg</p>
<table style="width:100%;margin-left:5px" >
    <tr >
        <td>
            <table id="itemPlaceholderContainer" style="word-break:break-all;background-color: #FFFFFF;border-collapse: collapse;border-color: #999999;border-style:solid;border-width:1px;display:block;width:100%">
                <colgroup>
                    <col style="width:auto" />
                    <col style="width:100px" />
                    <col style="width:35%;" />
                    <col style="width:5%;" />
                    <col style="width:10%" />
                </colgroup>
                <tr style="background-color: #E0FFFF;color: #333333;">
                    <th>网址</th>
                    <th>图片</th>
                    <th>标题</th>
                    <th>点击</th>
                    <th>操作</th>
                </tr>
                @{int i = 0;
                  if(Model!=null){
                  foreach (var Item in Model)
                  {
                <tr style="background-color: @(i++ % 2 == 0 ? "#FFFFFF" : "#E0FFFF");color: #333333;display:none;" id="tre@(Item.AdID)">
                    <td>
                        <input type="text" id="editurl@(Item.AdID)" value="@Item.AdUrl" />
                    </td>
                    <td>
                        <input type="text" id="editimg@(Item.AdID)" value="@Item.ImgUrl" />
                    </td>
                    <td>
                        <input type="text" id="edittitle@(Item.AdID)" value="@Item.AdTitle" />
                    </td>
                    <td>
                        @Item.ClickCount
                    </td>
                    <td>
                        <Button ID="Cancel" name="@Item.AdID" >取消</Button><Button ID="Submit" name="@Item.AdID" >确认</Button>
                    </td>
                </tr>
                <tr style="background-color: @(i % 2 == 0 ? "#FFFFFF" : "#E0FFFF");color: #333333;" id="tr@(Item.AdID)">
                    <td>
                        @Item.AdUrl
                    </td>
                    <td>
                        <img src="@Item.ImgUrl" style="max-width:100px;max-height:100px;"/>
                    </td>
                    <td>
                        @Item.AdTitle
                    </td>
                    <td>
                        @Item.ClickCount
                    </td>
                    <td>
                        <Button ID="Del" name="@Item.AdID" >删除</Button><Button ID="Edit" name="@Item.AdID" >编辑</Button>
                    </td>
                </tr>
                    }
                    }
                }
                <tr>
                    <td>
                        <input type="text" id="newurl" value="" data-val="true" maxlength="1000" data-val-required="请输入URL"/>
                    </td>
                    <td>
                        <input type="text" id="newimg" value="" data-val="true" maxlength="1000" data-val-required="请输入图片"/>
                    </td>
                    <td>
                        <input type="text" id="newtitle" value="" data-val="true" maxlength="100" data-val-required="请输入标题" />
                    </td>
                    <td></td>
                    <td>
                        <Button ID="New">添加</Button>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
@using (Html.BeginForm("AdManage", "Advertisment", FormMethod.Post, new { id = "manageads" }))
{
    @Html.AntiForgeryToken();
    <input type="hidden" name="AdID" id="AdID" />
    <input type="hidden" name="AdUrl" id="AdUrl" />
    <input type="hidden" name="AdImg" id="AdImg" />
    <input type="hidden" name="AdTitle" id="AdTitle" />
    <input type="hidden" name="action" id="action" />
}

@section end_scripts{
<script>
    var title = {}; var url = {}; var img = {};
    $("Button#Edit").click(function () {
        var $this = $(this);
        var id = $this.attr('name');
        $('#tr'+id).hide();
        $('#tre' + id).show();
        title[id] = $('#edittitle' + id).val();
        url[id] = $('#editurl' + id).val();
        img[id] = $('#editimg' + id).val();
    });
    $("Button#Cancel").click(function () {
        var $this = $(this);
        var id = $this.attr('name');
        $('#tre' + id).hide();
        $('#tr' + id).show();
        $('#edittitle' + id).val(title[id]);
        $('#editurl' + id).val(url[id]);
        $('#editimg' + id).val(img[id]);
    });
    $("Button#Del").click(function () {
        if (confirm("确认删除？")) {
            var $this = $(this);
            var id = $this.attr('name');
            $('#AdID').val(id);
            $('#action').val('del');
            $('#manageads').submit();
        }
    });
    $("Button#Submit").click(function () {
        var $this = $(this);
        var id = $this.attr('name');
        $('#AdID').val(id);
        title[id] = $('#edittitle' + id).val();
        url[id] = $('#editurl' + id).val();
        img[id] = $('#editimg' + id).val();
        $('#AdTitle').val(title[id]);
        $('#AdUrl').val(url[id]);
        $('#AdImg').val(img[id]);
        $('#action').val('edit');
        $('#manageads').submit();
    });
    $("Button#New").click(function () {
        var nurl = $('#newurl').val();
        var ntitle = $('#newtitle').val();
        var nimg = $('#newimg').val();
        $('#AdTitle').val(ntitle);
        $('#AdUrl').val(nurl);
        $('#AdImg').val(nimg);
        $('#action').val('new');
        $('#manageads').submit();
    });
</script>
}

MyWebSite/Views/Advertisment/_AdPartial.cshtml
@model List<MyMVCWeb.Models.Advertisment>

@if(Model != null && Model.Count > 0){
    <h3>绅士周边：</h3>
<div>
<script src="~/Scripts/jquery.cycle2.min.js"></script>
    <style>
        .addiv img
        {
            max-height:80px !important;
            max-width:80px !important;
        }
        .thumbnails .span2
        {
            width:125px;
        }
    </style>
<div class="cycle-slideshow addiv hide" 
    data-cycle-fx="scrollHorz" 
    data-cycle-timeout="10000"
    data-cycle-slides="> div"
    >
    <div>
        <ul class="thumbnails">
            @{ int i = 0;
            foreach (var item in Model)
            {
                <li class="span2">
                    <a rel="nofollow" onclick="clickad(this)" target="_blank" data-id="@item.AdID" href="@item.AdUrl" class="thumbnail">
                        <img src="@item.ImgUrl" alt="@item.AdTitle"/>
                        <div class="caption">
                            @item.AdTitle
                        </div>
                    </a>
                </li>
                if (++i % 5 == 0)
                {
                    @Html.Raw("</ul></div><div><ul class='thumbnails'>")
                }
            }
            }
        </ul>
    </div>
</div>
    <script>
        function clickad(ele) {
            var id = $(ele).attr('data-id');
            alert(id);
            if (id) {
                $.post('@Url.Action("Click","Advertisment")', { adid: id }, $.noop);
            }
            return true;
        }
        $(function () {
            $('.addiv').removeClass('hide');
        });
    </script>
</div>
}